spring:
  application:
    name: challkathon-demo
  
  profiles:
    active: local  # 기본 프로파일을 local로 설정

  # JPA 기본 설정
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7831406ec88574ac2d16c5a3c2445a28
            client-secret: KaswvWWXLzw6eHPf5oHOTrZmRooVxjQr
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# JWT 설정
jwt:
  secret: ${JWT_SECRET:CHANGE_THIS_TO_RANDOM_SECRET_KEY_MIN_64_CHARS_FOR_HS512_ALGORITHM_SECURITY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}    # 1시간 (밀리초)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7일 (밀리초)
  issuer: ${JWT_ISSUER:challkathon-demo}

# 앱 설정
app:
  oauth2:
    authorized-redirect-uris: ${AUTHORIZED_REDIRECT_URIS:http://localhost:3000/oauth2/redirect,http://localhost:8080/oauth2/redirect}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

# 서버 설정
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정 (디버그용)
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.security.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    com.challkathon.demo: DEBUG

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
