spring:
  application:
    name: challkathon-demo
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 환경 변수로 프로파일 선택, 기본값은 local

  # JPA 기본 설정
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# JWT 설정 (공통)
jwt:
  secret: dkfjslkdfjsldfkjdigasjodgiajsdiojsfoijdfsmdivmcvkzxjclvkvmzxcweifuoidf
  access-token-expiration: 3600000    # 1시간 (밀리초)
  refresh-token-expiration: 604800000 # 7일 (밀리초)
  issuer: challkathon-demo

# 앱 설정 (기본값)
app:
  oauth2:
    authorized-redirect-uris: ${AUTHORIZED_REDIRECT_URIS:http://localhost:3000/oauth2/redirect,http://localhost:8080/oauth2/redirect}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
  cookie:
    refresh-token:
      name: ${COOKIE_REFRESH_TOKEN_NAME:refreshToken}
      max-age: ${COOKIE_REFRESH_TOKEN_MAX_AGE:604800}  # 7일 (초 단위)
      domain: ${COOKIE_DOMAIN:localhost}
      secure: ${COOKIE_SECURE:false}

# 서버 설정 (공통)
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정 (기본값)
logging:
  level:
    com.challkathon.demo: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

# Swagger 설정 (공통)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
